name: Pack Completeness Check

on:
  pull_request:
    paths:
      - 'packs/**'

jobs:
  enforce-compounding-rule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3
      
      - name: Check Pack Structure
        run: |
          mkdir -p .github/scripts
          python3 .github/scripts/check_completeness.py
